title: Tequa Builders
email: jd@tequabuilders.com
description: Make your dream home a reality!
baseurl: ""
url: "http://tequabuilders.com"
logo: /img/logo-lrg.png


# Build settings
markdown: kramdown
# theme: minima
permalink: pretty

# Compress Sass
sass:
  style: compressed

# Gems / Plugins
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at